class Receipt:

    def __init__(self, store_name="", date="", store_address="", products=[]) -> None:
        self.pk = "None" #generated by mongo
        self.sk = "None" # date#store
        self.store_name = store_name
        self.store_address = store_address
        self.products = products #list of product objects
        self.date = date

    def print(self) -> None:
        '''print info stores in model'''
        print("Store Name: ", self.store_name)
        print("Date: ", self.date)
        print("Address: ", self.store_address)
        print("Products: ")

        for item_number, product in enumerate(self.products):
            print("----------Product ", item_number + 1, "----------")
            product.print()

    def getMap(self):
         '''convert model to map for use in jsonify()'''
         return{
            "pk": self.pk,
            "sk": self.sk,
            "store_name": self.store_name,
            "date": self.date, 
            "products": [product.__dict__ for product in self.products]
        }
